ALTER TABLE "Order" ADD COLUMN "clienteId" TEXT;
ALTER TABLE "Order" ALTER COLUMN "empleadoId" DROP NOT NULL;

ALTER TABLE "Order" ADD CONSTRAINT "Order_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
